driver:
  name: vagrant
  customize:
    nictype1: virtio

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.2.20

platforms:
  - name: debian-8.8

suites:
  - name: install
    run_list:
      - recipe[test::install]
  - name: remove
    run_list:
      - recipe[test::remove]
