# n.b kitchen-dokken works exclusively with Chef i.e there's no Cinc support
# Chef Infra Client cannot execute without accepting the license - erm, no

driver:
  name: docker
  privileged: true
  use_sudo: false

transport:
  name: docker

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: 16.11.7

platforms:
- name: debian-10

suites:
- name: install
  run_list:
  - recipe[test::test]
  - recipe[test::install]
- name: remove
  run_list:
  - recipe[test::test]
  - recipe[test::remove]
