driver:
  name: vagrant
  customize:
    nictype1: virtio

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.2.20

platforms:
  - name: debian/jessie64

suites:
  - name: test_install
    run_list:
      - recipe[remote_apt::test_install]
  - name: test_remove
    run_list:
      - recipe[remote_apt::test_remove]
